# Japanese translation for ubuntuone-client
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the ubuntuone-client package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: ubuntuone-client\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2012-09-10 21:26+0000\n"
"PO-Revision-Date: 2012-04-18 23:31+0000\n"
"Last-Translator: Shushi Kurose <md81bird@hitaki.net>\n"
"Language-Team: Japanese <ja@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Launchpad-Export-Date: 2012-09-17 18:32+0000\n"
"X-Generator: Launchpad (build 15966)\n"

#: ../ubuntuone/status/aggregator.py:51
msgid "Magicicada"
msgstr "Magicicada"

#: ../ubuntuone/status/aggregator.py:52
msgid "New cloud folder(s) available"
msgstr "新しいクラウドフォルダーが利用できます"

#: ../ubuntuone/status/aggregator.py:53
msgid "File synchronization completed."
msgstr "ファイルの同期が完了しました。"

#: ../ubuntuone/status/aggregator.py:55
#, python-format
msgid "%(percentage_completed)d%% completed."
msgstr "%(percentage_completed)d%% 完了。"

#: ../ubuntuone/status/aggregator.py:56
msgid "File synchronization in progress"
msgstr "ファイルの同期中"

#: ../ubuntuone/status/aggregator.py:59
#, python-format
msgid ""
"There is no available space on the folder:\n"
"\"%s\" shared by %s"
msgstr ""
"フォルダーに利用できる空き領域がありません:\n"
"\"%s\" は %s によって共有されています"

#: ../ubuntuone/status/aggregator.py:73
#, python-format
msgid "'%(filename)s' is being uploaded to your personal cloud."
msgstr "'%(filename)s' をパーソナルクラウドにアップロードしています。"

#: ../ubuntuone/status/aggregator.py:79
#, python-format
msgid ""
"'%(filename)s' and %(other_files)d other file are being uploaded to your "
"personal cloud."
msgid_plural ""
"'%(filename)s' and %(other_files)d other files are being uploaded to your "
"personal cloud."
msgstr[0] ""
"'%(filename)s' と他 %(other_files)d 個のファイルがあなたのパーソナルクラウドにアップロードされています。"

#: ../ubuntuone/status/aggregator.py:90
#, python-format
msgid "'%(filename)s' is being downloaded to your computer."
msgstr "'%(filename)s' をコンピューターにダウンロードしています。"

#: ../ubuntuone/status/aggregator.py:96
#, python-format
msgid ""
"'%(filename)s' and %(other_files)d other file are being downloaded to your "
"computer."
msgid_plural ""
"'%(filename)s' and %(other_files)d other files are being downloaded to your "
"computer."
msgstr[0] ""
"'%(filename)s' と他 %(other_files)d 個のファイルがあなたのコンピューターにダウンロードされています。"

#: ../ubuntuone/status/aggregator.py:107
#, python-format
msgid "'%(filename)s' was uploaded to your personal cloud."
msgstr "'%(filename)s' がパーソナルクラウドにアップロードされました。"

#: ../ubuntuone/status/aggregator.py:113
#, python-format
msgid ""
"'%(filename)s' and %(other_files)d other file were uploaded to your personal "
"cloud."
msgid_plural ""
"'%(filename)s' and %(other_files)d other files were uploaded to your "
"personal cloud."
msgstr[0] ""
"'%(filename)s' と他 %(other_files)d 個のファイルがあなたのパーソナルクラウドにアップロードされました。"

#: ../ubuntuone/status/aggregator.py:124
#, python-format
msgid "'%(filename)s' was downloaded to your computer."
msgstr "'%(filename)s' がコンピューターにダウンロードされました。"

#: ../ubuntuone/status/aggregator.py:130
#, python-format
msgid ""
"'%(filename)s' and %(other_files)d other file were downloaded to your "
"computer."
msgid_plural ""
"'%(filename)s' and %(other_files)d other files were downloaded to your "
"computer."
msgstr[0] "'%(filename)s' と他 %(other_files)d 個のファイルがあなたのコンピューターにダウンロードされました。"

#: ../ubuntuone/status/aggregator.py:191
#, python-format
msgid "A file was just made public at %(new_public_url)s"
msgstr "ファイルが %(new_public_url)s として公開されました"

#: ../ubuntuone/status/aggregator.py:204
#, python-format
msgid "%(event_count)d file was just made public."
msgid_plural "%(event_count)d files were just made public."
msgstr[0] "%(event_count)d 個のファイルが公開されました。"

#: ../ubuntuone/status/aggregator.py:212
msgid "A file is no longer published"
msgstr "ファイルの公開を停止しました"

#: ../ubuntuone/status/aggregator.py:220
#, python-format
msgid "%(event_count)d file is no longer published."
msgid_plural "%(event_count)d files are no longer published."
msgstr[0] "%(event_count)d 個のファイルの公開を停止しました。"

#: ../ubuntuone/status/aggregator.py:235
#, python-format
msgid "Found %(event_count)d new cloud folder."
msgid_plural "Found %(event_count)d new cloud folders."
msgstr[0] "新しいクラウドフォルダー %(event_count)d が見つかりました。"

#: ../ubuntuone/status/aggregator.py:243
#, python-format
msgid ""
"New cloud folder available: '%(folder_name)s' shared by %(other_user_name)s"
msgstr "新しいクラウドフォルダー: '%(folder_name)s' が %(other_user_name)s によって共有されました"

#: ../ubuntuone/status/aggregator.py:259
#, python-format
msgid "New cloud folder available: '%(folder_name)s'"
msgstr "新しいクラウドフォルダー : '%(folder_name)s'"

#: ../ubuntuone/status/aggregator.py:281
msgid "The connection to the server was lost."
msgstr "サーバとの接続が失われました。"

#: ../ubuntuone/status/aggregator.py:287
msgid "The connection to the server was restored."
msgstr "サーバーへの接続が復帰しました。"

#: ../data/emblem-ubuntuone-downloading.icon.in.h:1
msgid "Downloading"
msgstr "ダウンロード中"

#: ../data/emblem-ubuntuone-unsynchronized.icon.in.h:1
msgid "Unsynchronized"
msgstr "同期されていません"

#: ../data/emblem-ubuntuone-uploading.icon.in.h:1
msgid "Uploading"
msgstr "アップロード中"
